// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodePort : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphNodePort GetRootAsGraphNodePort(ByteBuffer _bb) { return GetRootAsGraphNodePort(_bb, new GraphNodePort()); }
  public static GraphNodePort GetRootAsGraphNodePort(ByteBuffer _bb, GraphNodePort obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphNodePort __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase? Identity { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public int ArgumentTypes { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static void StartGraphNodePort(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIdentity(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase> identityOffset) { builder.AddStruct(0, identityOffset.Value, 0); }
  public static void AddArgumentTypes(FlatBufferBuilder builder, int argumentTypes) { builder.AddInt(1, argumentTypes, 0); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort> EndGraphNodePort(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // identity
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>(o);
  }
}


static public class GraphNodePortVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Identity*/, 8 /*ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase*/, 4, true)
      && verifier.VerifyField(tablePos, 6 /*ArgumentTypes*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
