// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphContainer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphContainer GetRootAsGraphContainer(ByteBuffer _bb) { return GetRootAsGraphContainer(_bb, new GraphContainer()); }
  public static GraphContainer GetRootAsGraphContainer(ByteBuffer _bb, GraphContainer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphContainer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphNodeData? Nodes(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeData?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NodesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Graph.GraphNodeTray? Trays(int j) { int o = __p.__offset(6); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeTray?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeTray()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TraysLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Graph.GraphLinkData? SignalLinks(int j) { int o = __p.__offset(8); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphLinkData?)(new ReblackVfx.FlatBuffer.Graph.GraphLinkData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SignalLinksLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Graph.GraphLinkData? PropertyLinks(int j) { int o = __p.__offset(10); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphLinkData?)(new ReblackVfx.FlatBuffer.Graph.GraphLinkData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropertyLinksLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer> CreateGraphContainer(FlatBufferBuilder builder,
      VectorOffset nodesOffset = default(VectorOffset),
      VectorOffset traysOffset = default(VectorOffset),
      VectorOffset signal_linksOffset = default(VectorOffset),
      VectorOffset property_linksOffset = default(VectorOffset)) {
    builder.StartTable(4);
    GraphContainer.AddPropertyLinks(builder, property_linksOffset);
    GraphContainer.AddSignalLinks(builder, signal_linksOffset);
    GraphContainer.AddTrays(builder, traysOffset);
    GraphContainer.AddNodes(builder, nodesOffset);
    return GraphContainer.EndGraphContainer(builder);
  }

  public static void StartGraphContainer(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddNodes(FlatBufferBuilder builder, VectorOffset nodesOffset) { builder.AddOffset(0, nodesOffset.Value, 0); }
  public static VectorOffset CreateNodesVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNodesVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNodesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNodesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartNodesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTrays(FlatBufferBuilder builder, VectorOffset traysOffset) { builder.AddOffset(1, traysOffset.Value, 0); }
  public static VectorOffset CreateTraysVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTraysVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTraysVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTraysVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTraysVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSignalLinks(FlatBufferBuilder builder, VectorOffset signalLinksOffset) { builder.AddOffset(2, signalLinksOffset.Value, 0); }
  public static VectorOffset CreateSignalLinksVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSignalLinksVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSignalLinksVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSignalLinksVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSignalLinksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPropertyLinks(FlatBufferBuilder builder, VectorOffset propertyLinksOffset) { builder.AddOffset(3, propertyLinksOffset.Value, 0); }
  public static VectorOffset CreatePropertyLinksVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertyLinksVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertyLinksVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertyLinksVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPropertyLinksVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer> EndGraphContainer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // nodes
    builder.Required(o, 6);  // trays
    builder.Required(o, 8);  // signal_links
    builder.Required(o, 10);  // property_links
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer>(o);
  }
}


static public class GraphContainerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Nodes*/, ReblackVfx.FlatBuffer.Graph.GraphNodeDataVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Trays*/, ReblackVfx.FlatBuffer.Graph.GraphNodeTrayVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*SignalLinks*/, ReblackVfx.FlatBuffer.Graph.GraphLinkDataVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*PropertyLinks*/, ReblackVfx.FlatBuffer.Graph.GraphLinkDataVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
