// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphHeader : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphHeader GetRootAsGraphHeader(ByteBuffer _bb) { return GetRootAsGraphHeader(_bb, new GraphHeader()); }
  public static GraphHeader GetRootAsGraphHeader(ByteBuffer _bb, GraphHeader obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphHeader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphVersionInfo? Version { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphVersionInfo?)(new ReblackVfx.FlatBuffer.Graph.GraphVersionInfo()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartGraphHeader(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddVersion(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphVersionInfo> versionOffset) { builder.AddStruct(0, versionOffset.Value, 0); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphHeader> EndGraphHeader(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // version
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphHeader>(o);
  }
}


static public class GraphHeaderVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Version*/, 12 /*ReblackVfx.FlatBuffer.Graph.GraphVersionInfo*/, 4, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
