// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphLinkData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphLinkData GetRootAsGraphLinkData(ByteBuffer _bb) { return GetRootAsGraphLinkData(_bb, new GraphLinkData()); }
  public static GraphLinkData GetRootAsGraphLinkData(ByteBuffer _bb, GraphLinkData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphLinkData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int InstanceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int SourceNodeId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int SourceMemberId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DestinationNodeId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DestinationMemberId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int LinkType { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Unknown { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData> CreateGraphLinkData(FlatBufferBuilder builder,
      int instance_id = 0,
      int source_node_id = 0,
      int source_member_id = 0,
      int destination_node_id = 0,
      int destination_member_id = 0,
      int link_type = 0,
      int unknown = 0) {
    builder.StartTable(7);
    GraphLinkData.AddUnknown(builder, unknown);
    GraphLinkData.AddLinkType(builder, link_type);
    GraphLinkData.AddDestinationMemberId(builder, destination_member_id);
    GraphLinkData.AddDestinationNodeId(builder, destination_node_id);
    GraphLinkData.AddSourceMemberId(builder, source_member_id);
    GraphLinkData.AddSourceNodeId(builder, source_node_id);
    GraphLinkData.AddInstanceId(builder, instance_id);
    return GraphLinkData.EndGraphLinkData(builder);
  }

  public static void StartGraphLinkData(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddInstanceId(FlatBufferBuilder builder, int instanceId) { builder.AddInt(0, instanceId, 0); }
  public static void AddSourceNodeId(FlatBufferBuilder builder, int sourceNodeId) { builder.AddInt(1, sourceNodeId, 0); }
  public static void AddSourceMemberId(FlatBufferBuilder builder, int sourceMemberId) { builder.AddInt(2, sourceMemberId, 0); }
  public static void AddDestinationNodeId(FlatBufferBuilder builder, int destinationNodeId) { builder.AddInt(3, destinationNodeId, 0); }
  public static void AddDestinationMemberId(FlatBufferBuilder builder, int destinationMemberId) { builder.AddInt(4, destinationMemberId, 0); }
  public static void AddLinkType(FlatBufferBuilder builder, int linkType) { builder.AddInt(5, linkType, 0); }
  public static void AddUnknown(FlatBufferBuilder builder, int unknown) { builder.AddInt(6, unknown, 0); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData> EndGraphLinkData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphLinkData>(o);
  }
}


static public class GraphLinkDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*InstanceId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*SourceNodeId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*SourceMemberId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*DestinationNodeId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*DestinationMemberId*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*LinkType*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Unknown*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
