// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodeData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphNodeData GetRootAsGraphNodeData(ByteBuffer _bb) { return GetRootAsGraphNodeData(_bb, new GraphNodeData()); }
  public static GraphNodeData GetRootAsGraphNodeData(ByteBuffer _bb, GraphNodeData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphNodeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase? Identity { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ReblackVfx.FlatBuffer.Graph.GraphNodeProperty? Properties(int j) { int o = __p.__offset(6); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeProperty?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeProperty()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PropertiesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Graph.GraphNodePort? InPorts(int j) { int o = __p.__offset(8); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodePort?)(new ReblackVfx.FlatBuffer.Graph.GraphNodePort()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int InPortsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Graph.GraphNodePort? OutPorts(int j) { int o = __p.__offset(10); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodePort?)(new ReblackVfx.FlatBuffer.Graph.GraphNodePort()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OutPortsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static void StartGraphNodeData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddIdentity(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase> identityOffset) { builder.AddStruct(0, identityOffset.Value, 0); }
  public static void AddProperties(FlatBufferBuilder builder, VectorOffset propertiesOffset) { builder.AddOffset(1, propertiesOffset.Value, 0); }
  public static VectorOffset CreatePropertiesVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePropertiesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInPorts(FlatBufferBuilder builder, VectorOffset inPortsOffset) { builder.AddOffset(2, inPortsOffset.Value, 0); }
  public static VectorOffset CreateInPortsVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInPortsVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInPortsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInPortsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInPortsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOutPorts(FlatBufferBuilder builder, VectorOffset outPortsOffset) { builder.AddOffset(3, outPortsOffset.Value, 0); }
  public static VectorOffset CreateOutPortsVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOutPortsVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutPortsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutPortsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Graph.GraphNodePort>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOutPortsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData> EndGraphNodeData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // identity
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeData>(o);
  }
}


static public class GraphNodeDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Identity*/, 8 /*ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase*/, 4, true)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Properties*/, ReblackVfx.FlatBuffer.Graph.GraphNodePropertyVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*InPorts*/, ReblackVfx.FlatBuffer.Graph.GraphNodePortVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*OutPorts*/, ReblackVfx.FlatBuffer.Graph.GraphNodePortVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
