// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodeTray : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphNodeTray GetRootAsGraphNodeTray(ByteBuffer _bb) { return GetRootAsGraphNodeTray(_bb, new GraphNodeTray()); }
  public static GraphNodeTray GetRootAsGraphNodeTray(ByteBuffer _bb, GraphNodeTray obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphNodeTray __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint InstanceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint TypeId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint References(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int ReferencesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetReferencesBytes() { return __p.__vector_as_span<uint>(8, 4); }
#else
  public ArraySegment<byte>? GetReferencesBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public uint[] GetReferencesArray() { return __p.__vector_as_array<uint>(8); }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray> CreateGraphNodeTray(FlatBufferBuilder builder,
      uint instance_id = 0,
      uint type_id = 0,
      VectorOffset referencesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    GraphNodeTray.AddReferences(builder, referencesOffset);
    GraphNodeTray.AddTypeId(builder, type_id);
    GraphNodeTray.AddInstanceId(builder, instance_id);
    return GraphNodeTray.EndGraphNodeTray(builder);
  }

  public static void StartGraphNodeTray(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddInstanceId(FlatBufferBuilder builder, uint instanceId) { builder.AddUint(0, instanceId, 0); }
  public static void AddTypeId(FlatBufferBuilder builder, uint typeId) { builder.AddUint(1, typeId, 0); }
  public static void AddReferences(FlatBufferBuilder builder, VectorOffset referencesOffset) { builder.AddOffset(2, referencesOffset.Value, 0); }
  public static VectorOffset CreateReferencesVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateReferencesVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateReferencesVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateReferencesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartReferencesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray> EndGraphNodeTray(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 8);  // references
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeTray>(o);
  }
}


static public class GraphNodeTrayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*InstanceId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*TypeId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*References*/, 4 /*uint*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
