// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphBinary : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphBinary GetRootAsGraphBinary(ByteBuffer _bb) { return GetRootAsGraphBinary(_bb, new GraphBinary()); }
  public static GraphBinary GetRootAsGraphBinary(ByteBuffer _bb, GraphBinary obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphBinary __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphHeader? GraphHeader { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphHeader?)(new ReblackVfx.FlatBuffer.Graph.GraphHeader()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ReblackVfx.FlatBuffer.Graph.GraphContainer? GraphContainer { get { int o = __p.__offset(6); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphContainer?)(new ReblackVfx.FlatBuffer.Graph.GraphContainer()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData? BaseTypeData { get { int o = __p.__offset(8); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData?)(new ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary> CreateGraphBinary(FlatBufferBuilder builder,
      Offset<ReblackVfx.FlatBuffer.Graph.GraphHeader> graph_headerOffset = default(Offset<ReblackVfx.FlatBuffer.Graph.GraphHeader>),
      Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer> graph_containerOffset = default(Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer>),
      Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData> base_type_dataOffset = default(Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData>)) {
    builder.StartTable(3);
    GraphBinary.AddBaseTypeData(builder, base_type_dataOffset);
    GraphBinary.AddGraphContainer(builder, graph_containerOffset);
    GraphBinary.AddGraphHeader(builder, graph_headerOffset);
    return GraphBinary.EndGraphBinary(builder);
  }

  public static void StartGraphBinary(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddGraphHeader(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphHeader> graphHeaderOffset) { builder.AddOffset(0, graphHeaderOffset.Value, 0); }
  public static void AddGraphContainer(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphContainer> graphContainerOffset) { builder.AddOffset(1, graphContainerOffset.Value, 0); }
  public static void AddBaseTypeData(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData> baseTypeDataOffset) { builder.AddOffset(2, baseTypeDataOffset.Value, 0); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary> EndGraphBinary(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // graph_header
    builder.Required(o, 6);  // graph_container
    builder.Required(o, 8);  // base_type_data
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary>(o);
  }
}


static public class GraphBinaryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*GraphHeader*/, ReblackVfx.FlatBuffer.Graph.GraphHeaderVerify.Verify, true)
      && verifier.VerifyTable(tablePos, 6 /*GraphContainer*/, ReblackVfx.FlatBuffer.Graph.GraphContainerVerify.Verify, true)
      && verifier.VerifyTable(tablePos, 8 /*BaseTypeData*/, ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeDataVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
