// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodeMemberBase : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GraphNodeMemberBase __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MemberId { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint NameHash { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase> CreateGraphNodeMemberBase(FlatBufferBuilder builder, uint MemberId, uint NameHash) {
    builder.Prep(4, 8);
    builder.PutUint(NameHash);
    builder.PutUint(MemberId);
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase>(builder.Offset);
  }
}


}
