// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphVersionInfo : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GraphVersionInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Self { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint Tool { get { return __p.bb.GetUint(__p.bb_pos + 4); } }
  public uint Converter { get { return __p.bb.GetUint(__p.bb_pos + 8); } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphVersionInfo> CreateGraphVersionInfo(FlatBufferBuilder builder, uint Self, uint Tool, uint Converter) {
    builder.Prep(4, 12);
    builder.PutUint(Converter);
    builder.PutUint(Tool);
    builder.PutUint(Self);
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphVersionInfo>(builder.Offset);
  }
}


}
