// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodeProperty : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphNodeProperty GetRootAsGraphNodeProperty(ByteBuffer _bb) { return GetRootAsGraphNodeProperty(_bb, new GraphNodeProperty()); }
  public static GraphNodeProperty GetRootAsGraphNodeProperty(ByteBuffer _bb, GraphNodeProperty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphNodeProperty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase? Identity { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase?)(new ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public int ValueTable { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public ReblackVfx.FlatBuffer.BaseType.Value? ValueReference { get { int o = __p.__offset(8); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Value?)(new ReblackVfx.FlatBuffer.BaseType.Value()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartGraphNodeProperty(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddIdentity(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase> identityOffset) { builder.AddStruct(0, identityOffset.Value, 0); }
  public static void AddValueTable(FlatBufferBuilder builder, int valueTable) { builder.AddInt(1, valueTable, 0); }
  public static void AddValueReference(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Value> valueReferenceOffset) { builder.AddStruct(2, valueReferenceOffset.Value, 0); }
  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty> EndGraphNodeProperty(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // identity
    builder.Required(o, 8);  // value_reference
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeProperty>(o);
  }
}


static public class GraphNodePropertyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Identity*/, 8 /*ReblackVfx.FlatBuffer.Graph.GraphNodeMemberBase*/, 4, true)
      && verifier.VerifyField(tablePos, 6 /*ValueTable*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*ValueReference*/, 8 /*ReblackVfx.FlatBuffer.BaseType.Value*/, 4, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
