// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Graph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphNodeDataBase : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GraphNodeDataBase __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint InstanceId { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint TypeId { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase> CreateGraphNodeDataBase(FlatBufferBuilder builder, uint InstanceId, uint TypeId) {
    builder.Prep(4, 8);
    builder.PutUint(TypeId);
    builder.PutUint(InstanceId);
    return new Offset<ReblackVfx.FlatBuffer.Graph.GraphNodeDataBase>(builder.Offset);
  }
}


}
