// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Matrix34 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Matrix34 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Math.Vector4 Row0 { get { return (new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.bb_pos + 0, __p.bb); } }
  public ReblackVfx.FlatBuffer.Math.Vector4 Row1 { get { return (new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.bb_pos + 16, __p.bb); } }
  public ReblackVfx.FlatBuffer.Math.Vector4 Row2 { get { return (new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.bb_pos + 32, __p.bb); } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Matrix34> CreateMatrix34(FlatBufferBuilder builder, float row_0_X, float row_0_Y, float row_0_Z, float row_0_W, float row_1_X, float row_1_Y, float row_1_Z, float row_1_W, float row_2_X, float row_2_Y, float row_2_Z, float row_2_W) {
    builder.Prep(4, 48);
    builder.Prep(4, 16);
    builder.PutFloat(row_2_W);
    builder.PutFloat(row_2_Z);
    builder.PutFloat(row_2_Y);
    builder.PutFloat(row_2_X);
    builder.Prep(4, 16);
    builder.PutFloat(row_1_W);
    builder.PutFloat(row_1_Z);
    builder.PutFloat(row_1_Y);
    builder.PutFloat(row_1_X);
    builder.Prep(4, 16);
    builder.PutFloat(row_0_W);
    builder.PutFloat(row_0_Z);
    builder.PutFloat(row_0_Y);
    builder.PutFloat(row_0_X);
    return new Offset<ReblackVfx.FlatBuffer.Math.Matrix34>(builder.Offset);
  }
}


}
