// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Matrix34ArrayTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Matrix34ArrayTable GetRootAsMatrix34ArrayTable(ByteBuffer _bb) { return GetRootAsMatrix34ArrayTable(_bb, new Matrix34ArrayTable()); }
  public static Matrix34ArrayTable GetRootAsMatrix34ArrayTable(ByteBuffer _bb, Matrix34ArrayTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Matrix34ArrayTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Math.Matrix34? Data(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix34?)(new ReblackVfx.FlatBuffer.Math.Matrix34()).__assign(__p.__vector(o) + j * 48, __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable> CreateMatrix34ArrayTable(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Matrix34ArrayTable.AddData(builder, dataOffset);
    return Matrix34ArrayTable.EndMatrix34ArrayTable(builder);
  }

  public static void StartMatrix34ArrayTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(48, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable> EndMatrix34ArrayTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable>(o);
  }
}


static public class Matrix34ArrayTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Data*/, 48 /*ReblackVfx.FlatBuffer.Math.Matrix34*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
