// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Matrix44ArrayTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Matrix44ArrayTable GetRootAsMatrix44ArrayTable(ByteBuffer _bb) { return GetRootAsMatrix44ArrayTable(_bb, new Matrix44ArrayTable()); }
  public static Matrix44ArrayTable GetRootAsMatrix44ArrayTable(ByteBuffer _bb, Matrix44ArrayTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Matrix44ArrayTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Math.Matrix44? Data(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix44?)(new ReblackVfx.FlatBuffer.Math.Matrix44()).__assign(__p.__vector(o) + j * 64, __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable> CreateMatrix44ArrayTable(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Matrix44ArrayTable.AddData(builder, dataOffset);
    return Matrix44ArrayTable.EndMatrix44ArrayTable(builder);
  }

  public static void StartMatrix44ArrayTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(64, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable> EndMatrix44ArrayTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable>(o);
  }
}


static public class Matrix44ArrayTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Data*/, 64 /*ReblackVfx.FlatBuffer.Math.Matrix44*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
