// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct QuaternionArrayTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static QuaternionArrayTable GetRootAsQuaternionArrayTable(ByteBuffer _bb) { return GetRootAsQuaternionArrayTable(_bb, new QuaternionArrayTable()); }
  public static QuaternionArrayTable GetRootAsQuaternionArrayTable(ByteBuffer _bb, QuaternionArrayTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuaternionArrayTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Math.Quaternion? Data(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Quaternion?)(new ReblackVfx.FlatBuffer.Math.Quaternion()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable> CreateQuaternionArrayTable(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    QuaternionArrayTable.AddData(builder, dataOffset);
    return QuaternionArrayTable.EndQuaternionArrayTable(builder);
  }

  public static void StartQuaternionArrayTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable> EndQuaternionArrayTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable>(o);
  }
}


static public class QuaternionArrayTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Data*/, 16 /*ReblackVfx.FlatBuffer.Math.Quaternion*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
