// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector2 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Padding0 { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float Padding1 { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Vector2> CreateVector2(FlatBufferBuilder builder, float X, float Y, float Padding0, float Padding1) {
    builder.Prep(4, 16);
    builder.PutFloat(Padding1);
    builder.PutFloat(Padding0);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<ReblackVfx.FlatBuffer.Math.Vector2>(builder.Offset);
  }
}


}
