// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector4ArrayTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Vector4ArrayTable GetRootAsVector4ArrayTable(ByteBuffer _bb) { return GetRootAsVector4ArrayTable(_bb, new Vector4ArrayTable()); }
  public static Vector4ArrayTable GetRootAsVector4ArrayTable(ByteBuffer _bb, Vector4ArrayTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Vector4ArrayTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Math.Vector4? Data(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4?)(new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable> CreateVector4ArrayTable(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Vector4ArrayTable.AddData(builder, dataOffset);
    return Vector4ArrayTable.EndVector4ArrayTable(builder);
  }

  public static void StartVector4ArrayTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable> EndVector4ArrayTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable>(o);
  }
}


static public class Vector4ArrayTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Data*/, 16 /*ReblackVfx.FlatBuffer.Math.Vector4*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
