// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.Math
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector3 : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public int Padding { get { return __p.bb.GetInt(__p.bb_pos + 12); } }

  public static Offset<ReblackVfx.FlatBuffer.Math.Vector3> CreateVector3(FlatBufferBuilder builder, float X, float Y, float Z, int Padding) {
    builder.Prep(4, 16);
    builder.PutInt(Padding);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<ReblackVfx.FlatBuffer.Math.Vector3>(builder.Offset);
  }
}


}
