// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.VfxGraph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DummyTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static DummyTable GetRootAsDummyTable(ByteBuffer _bb) { return GetRootAsDummyTable(_bb, new DummyTable()); }
  public static DummyTable GetRootAsDummyTable(ByteBuffer _bb, DummyTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DummyTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Dummy { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable> CreateDummyTable(FlatBufferBuilder builder,
      int dummy = 0) {
    builder.StartTable(1);
    DummyTable.AddDummy(builder, dummy);
    return DummyTable.EndDummyTable(builder);
  }

  public static void StartDummyTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDummy(FlatBufferBuilder builder, int dummy) { builder.AddInt(0, dummy, 0); }
  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable> EndDummyTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>(o);
  }
}


static public class DummyTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Dummy*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
