// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.VfxGraph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FCurveAnchorPoint : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public FCurveAnchorPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Time { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint> CreateFCurveAnchorPoint(FlatBufferBuilder builder, float Time, float X, float Y, float Z) {
    builder.Prep(4, 16);
    builder.PutFloat(Z);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    builder.PutFloat(Time);
    return new Offset<ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint>(builder.Offset);
  }
}


}
