// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.VfxGraph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VfxFCurveData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static VfxFCurveData GetRootAsVfxFCurveData(ByteBuffer _bb) { return GetRootAsVfxFCurveData(_bb, new VfxFCurveData()); }
  public static VfxFCurveData GetRootAsVfxFCurveData(ByteBuffer _bb, VfxFCurveData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VfxFCurveData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int LoopIn { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int LoopOut { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CurveLoopType { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint? AnchorPoints(int j) { int o = __p.__offset(10); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint?)(new ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int AnchorPointsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData> CreateVfxFCurveData(FlatBufferBuilder builder,
      int loop_in = 0,
      int loop_out = 0,
      int curve_loop_type = 0,
      VectorOffset anchor_pointsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    VfxFCurveData.AddAnchorPoints(builder, anchor_pointsOffset);
    VfxFCurveData.AddCurveLoopType(builder, curve_loop_type);
    VfxFCurveData.AddLoopOut(builder, loop_out);
    VfxFCurveData.AddLoopIn(builder, loop_in);
    return VfxFCurveData.EndVfxFCurveData(builder);
  }

  public static void StartVfxFCurveData(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddLoopIn(FlatBufferBuilder builder, int loopIn) { builder.AddInt(0, loopIn, 0); }
  public static void AddLoopOut(FlatBufferBuilder builder, int loopOut) { builder.AddInt(1, loopOut, 0); }
  public static void AddCurveLoopType(FlatBufferBuilder builder, int curveLoopType) { builder.AddInt(2, curveLoopType, 0); }
  public static void AddAnchorPoints(FlatBufferBuilder builder, VectorOffset anchorPointsOffset) { builder.AddOffset(3, anchorPointsOffset.Value, 0); }
  public static void StartAnchorPointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData> EndVfxFCurveData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData>(o);
  }
}


static public class VfxFCurveDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*LoopIn*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*LoopOut*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*CurveLoopType*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*AnchorPoints*/, 16 /*ReblackVfx.FlatBuffer.VfxGraph.FCurveAnchorPoint*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
