// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.VfxGraph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VfxGraphBinary : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static VfxGraphBinary GetRootAsVfxGraphBinary(ByteBuffer _bb) { return GetRootAsVfxGraphBinary(_bb, new VfxGraphBinary()); }
  public static VfxGraphBinary GetRootAsVfxGraphBinary(ByteBuffer _bb, VfxGraphBinary obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VfxGraphBinaryBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "LMVG"); }
  public static bool VerifyVfxGraphBinary(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("LMVG", false, VfxGraphBinaryVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VfxGraphBinary __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.Graph.GraphBinary? GraphBinary { get { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.Graph.GraphBinary?)(new ReblackVfx.FlatBuffer.Graph.GraphBinary()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData? VfxTypeData { get { int o = __p.__offset(6); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData?)(new ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxGraphBinary> CreateVfxGraphBinary(FlatBufferBuilder builder,
      Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary> graph_binaryOffset = default(Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary>),
      Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData> vfx_type_dataOffset = default(Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData>)) {
    builder.StartTable(2);
    VfxGraphBinary.AddVfxTypeData(builder, vfx_type_dataOffset);
    VfxGraphBinary.AddGraphBinary(builder, graph_binaryOffset);
    return VfxGraphBinary.EndVfxGraphBinary(builder);
  }

  public static void StartVfxGraphBinary(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddGraphBinary(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Graph.GraphBinary> graphBinaryOffset) { builder.AddOffset(0, graphBinaryOffset.Value, 0); }
  public static void AddVfxTypeData(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData> vfxTypeDataOffset) { builder.AddOffset(1, vfxTypeDataOffset.Value, 0); }
  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxGraphBinary> EndVfxGraphBinary(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // graph_binary
    builder.Required(o, 6);  // vfx_type_data
    return new Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxGraphBinary>(o);
  }
  public static void FinishVfxGraphBinaryBuffer(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxGraphBinary> offset) { builder.Finish(offset.Value, "LMVG"); }
  public static void FinishSizePrefixedVfxGraphBinaryBuffer(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxGraphBinary> offset) { builder.FinishSizePrefixed(offset.Value, "LMVG"); }
}


static public class VfxGraphBinaryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*GraphBinary*/, ReblackVfx.FlatBuffer.Graph.GraphBinaryVerify.Verify, true)
      && verifier.VerifyTable(tablePos, 6 /*VfxTypeData*/, ReblackVfx.FlatBuffer.VfxGraph.VfxTypeDataVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
