// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.VfxGraph
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VfxTypeData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static VfxTypeData GetRootAsVfxTypeData(ByteBuffer _bb) { return GetRootAsVfxTypeData(_bb, new VfxTypeData()); }
  public static VfxTypeData GetRootAsVfxTypeData(ByteBuffer _bb, VfxTypeData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VfxTypeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? BoxData(int j) { int o = __p.__offset(4); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BoxDataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? SphereData(int j) { int o = __p.__offset(6); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SphereDataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? PointerData(int j) { int o = __p.__offset(8); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PointerDataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? VectorData(int j) { int o = __p.__offset(10); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int VectorDataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? OffsetData(int j) { int o = __p.__offset(12); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OffsetDataLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.DummyTable? OffsetArrayData(int j) { int o = __p.__offset(14); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.DummyTable?)(new ReblackVfx.FlatBuffer.VfxGraph.DummyTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OffsetArrayDataLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData? FCurveData(int j) { int o = __p.__offset(16); return o != 0 ? (ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData?)(new ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FCurveDataLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData> CreateVfxTypeData(FlatBufferBuilder builder,
      VectorOffset box_dataOffset = default(VectorOffset),
      VectorOffset sphere_dataOffset = default(VectorOffset),
      VectorOffset pointer_dataOffset = default(VectorOffset),
      VectorOffset vector_dataOffset = default(VectorOffset),
      VectorOffset offset_dataOffset = default(VectorOffset),
      VectorOffset offset_array_dataOffset = default(VectorOffset),
      VectorOffset f_curve_dataOffset = default(VectorOffset)) {
    builder.StartTable(7);
    VfxTypeData.AddFCurveData(builder, f_curve_dataOffset);
    VfxTypeData.AddOffsetArrayData(builder, offset_array_dataOffset);
    VfxTypeData.AddOffsetData(builder, offset_dataOffset);
    VfxTypeData.AddVectorData(builder, vector_dataOffset);
    VfxTypeData.AddPointerData(builder, pointer_dataOffset);
    VfxTypeData.AddSphereData(builder, sphere_dataOffset);
    VfxTypeData.AddBoxData(builder, box_dataOffset);
    return VfxTypeData.EndVfxTypeData(builder);
  }

  public static void StartVfxTypeData(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddBoxData(FlatBufferBuilder builder, VectorOffset boxDataOffset) { builder.AddOffset(0, boxDataOffset.Value, 0); }
  public static VectorOffset CreateBoxDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBoxDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoxDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoxDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBoxDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSphereData(FlatBufferBuilder builder, VectorOffset sphereDataOffset) { builder.AddOffset(1, sphereDataOffset.Value, 0); }
  public static VectorOffset CreateSphereDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSphereDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSphereDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSphereDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSphereDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPointerData(FlatBufferBuilder builder, VectorOffset pointerDataOffset) { builder.AddOffset(2, pointerDataOffset.Value, 0); }
  public static VectorOffset CreatePointerDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePointerDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePointerDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePointerDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPointerDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVectorData(FlatBufferBuilder builder, VectorOffset vectorDataOffset) { builder.AddOffset(3, vectorDataOffset.Value, 0); }
  public static VectorOffset CreateVectorDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateVectorDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVectorDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVectorDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVectorDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOffsetData(FlatBufferBuilder builder, VectorOffset offsetDataOffset) { builder.AddOffset(4, offsetDataOffset.Value, 0); }
  public static VectorOffset CreateOffsetDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOffsetDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOffsetDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOffsetDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOffsetDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOffsetArrayData(FlatBufferBuilder builder, VectorOffset offsetArrayDataOffset) { builder.AddOffset(5, offsetArrayDataOffset.Value, 0); }
  public static VectorOffset CreateOffsetArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOffsetArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOffsetArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOffsetArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.DummyTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOffsetArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFCurveData(FlatBufferBuilder builder, VectorOffset fCurveDataOffset) { builder.AddOffset(6, fCurveDataOffset.Value, 0); }
  public static VectorOffset CreateFCurveDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFCurveDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFCurveDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFCurveDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFCurveDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData> EndVfxTypeData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.VfxGraph.VfxTypeData>(o);
  }
}


static public class VfxTypeDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*BoxData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*SphereData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*PointerData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*VectorData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 12 /*OffsetData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*OffsetArrayData*/, ReblackVfx.FlatBuffer.VfxGraph.DummyTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 16 /*FCurveData*/, ReblackVfx.FlatBuffer.VfxGraph.VfxFCurveDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
