// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.BaseType
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DoubleArrayTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static DoubleArrayTable GetRootAsDoubleArrayTable(ByteBuffer _bb) { return GetRootAsDoubleArrayTable(_bb, new DoubleArrayTable()); }
  public static DoubleArrayTable GetRootAsDoubleArrayTable(ByteBuffer _bb, DoubleArrayTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DoubleArrayTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Data(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(__p.__vector(o) + j * 8) : (double)0; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<double> GetDataBytes() { return __p.__vector_as_span<double>(4, 8); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public double[] GetDataArray() { return __p.__vector_as_array<double>(4); }

  public static Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable> CreateDoubleArrayTable(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    DoubleArrayTable.AddData(builder, dataOffset);
    return DoubleArrayTable.EndDoubleArrayTable(builder);
  }

  public static void StartDoubleArrayTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddDouble(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<double> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<double>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable> EndDoubleArrayTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable>(o);
  }
}


static public class DoubleArrayTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Data*/, 8 /*double*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
