// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.BaseType
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GraphBaseTypeData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static GraphBaseTypeData GetRootAsGraphBaseTypeData(ByteBuffer _bb) { return GetRootAsGraphBaseTypeData(_bb, new GraphBaseTypeData()); }
  public static GraphBaseTypeData GetRootAsGraphBaseTypeData(ByteBuffer _bb, GraphBaseTypeData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GraphBaseTypeData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte ByteData(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  public int ByteDataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetByteDataBytes() { return __p.__vector_as_span<sbyte>(4, 1); }
#else
  public ArraySegment<byte>? GetByteDataBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public sbyte[] GetByteDataArray() { return __p.__vector_as_array<sbyte>(4); }
  public bool BoolData(int j) { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(__p.__vector(o) + j * 1) : false; }
  public int BoolDataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<bool> GetBoolDataBytes() { return __p.__vector_as_span<bool>(6, 1); }
#else
  public ArraySegment<byte>? GetBoolDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public bool[] GetBoolDataArray() { return __p.__vector_as_array<bool>(6); }
  public short Int16Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetShort(__p.__vector(o) + j * 2) : (short)0; }
  public int Int16DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<short> GetInt16DataBytes() { return __p.__vector_as_span<short>(8, 2); }
#else
  public ArraySegment<byte>? GetInt16DataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public short[] GetInt16DataArray() { return __p.__vector_as_array<short>(8); }
  public int Int32Data(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int Int32DataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetInt32DataBytes() { return __p.__vector_as_span<int>(10, 4); }
#else
  public ArraySegment<byte>? GetInt32DataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetInt32DataArray() { return __p.__vector_as_array<int>(10); }
  public long Int64Data(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int Int64DataLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetInt64DataBytes() { return __p.__vector_as_span<long>(12, 8); }
#else
  public ArraySegment<byte>? GetInt64DataBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public long[] GetInt64DataArray() { return __p.__vector_as_array<long>(12); }
  public byte UbyteData(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int UbyteDataLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUbyteDataBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetUbyteDataBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetUbyteDataArray() { return __p.__vector_as_array<byte>(14); }
  public ushort Uint16Data(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUshort(__p.__vector(o) + j * 2) : (ushort)0; }
  public int Uint16DataLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ushort> GetUint16DataBytes() { return __p.__vector_as_span<ushort>(16, 2); }
#else
  public ArraySegment<byte>? GetUint16DataBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public ushort[] GetUint16DataArray() { return __p.__vector_as_array<ushort>(16); }
  public uint Uint32Data(int j) { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int Uint32DataLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetUint32DataBytes() { return __p.__vector_as_span<uint>(18, 4); }
#else
  public ArraySegment<byte>? GetUint32DataBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public uint[] GetUint32DataArray() { return __p.__vector_as_array<uint>(18); }
  public ulong Uint64Data(int j) { int o = __p.__offset(20); return o != 0 ? __p.bb.GetUlong(__p.__vector(o) + j * 8) : (ulong)0; }
  public int Uint64DataLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ulong> GetUint64DataBytes() { return __p.__vector_as_span<ulong>(20, 8); }
#else
  public ArraySegment<byte>? GetUint64DataBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public ulong[] GetUint64DataArray() { return __p.__vector_as_array<ulong>(20); }
  public float FloatData(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int FloatDataLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetFloatDataBytes() { return __p.__vector_as_span<float>(22, 4); }
#else
  public ArraySegment<byte>? GetFloatDataBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public float[] GetFloatDataArray() { return __p.__vector_as_array<float>(22); }
  public double DoubleData(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetDouble(__p.__vector(o) + j * 8) : (double)0; }
  public int DoubleDataLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<double> GetDoubleDataBytes() { return __p.__vector_as_span<double>(24, 8); }
#else
  public ArraySegment<byte>? GetDoubleDataBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public double[] GetDoubleDataArray() { return __p.__vector_as_array<double>(24); }
  public string StringData(int j) { int o = __p.__offset(26); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int StringDataLength { get { int o = __p.__offset(26); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int EnumData(int j) { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int EnumDataLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetEnumDataBytes() { return __p.__vector_as_span<int>(28, 4); }
#else
  public ArraySegment<byte>? GetEnumDataBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public int[] GetEnumDataArray() { return __p.__vector_as_array<int>(28); }
  public ReblackVfx.FlatBuffer.Math.Vector4? Vector2Data(int j) { int o = __p.__offset(30); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4?)(new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int Vector2DataLength { get { int o = __p.__offset(30); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector4? Vector3Data(int j) { int o = __p.__offset(32); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4?)(new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int Vector3DataLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector4? Vector4Data(int j) { int o = __p.__offset(34); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4?)(new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int Vector4DataLength { get { int o = __p.__offset(34); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector4? ColorData(int j) { int o = __p.__offset(36); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4?)(new ReblackVfx.FlatBuffer.Math.Vector4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int ColorDataLength { get { int o = __p.__offset(36); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix33? Matrix33Data(int j) { int o = __p.__offset(38); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix33?)(new ReblackVfx.FlatBuffer.Math.Matrix33()).__assign(__p.__vector(o) + j * 48, __p.bb) : null; }
  public int Matrix33DataLength { get { int o = __p.__offset(38); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix34? Matrix34Data(int j) { int o = __p.__offset(40); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix34?)(new ReblackVfx.FlatBuffer.Math.Matrix34()).__assign(__p.__vector(o) + j * 48, __p.bb) : null; }
  public int Matrix34DataLength { get { int o = __p.__offset(40); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix44? Matrix44Data(int j) { int o = __p.__offset(42); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix44?)(new ReblackVfx.FlatBuffer.Math.Matrix44()).__assign(__p.__vector(o) + j * 64, __p.bb) : null; }
  public int Matrix44DataLength { get { int o = __p.__offset(42); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Quaternion? QuaternionData(int j) { int o = __p.__offset(44); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Quaternion?)(new ReblackVfx.FlatBuffer.Math.Quaternion()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int QuaternionDataLength { get { int o = __p.__offset(44); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Euler? EulerData(int j) { int o = __p.__offset(46); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Euler?)(new ReblackVfx.FlatBuffer.Math.Euler()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int EulerDataLength { get { int o = __p.__offset(46); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.ByteArrayTable? ByteArrayData(int j) { int o = __p.__offset(48); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.ByteArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.ByteArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ByteArrayDataLength { get { int o = __p.__offset(48); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.BoolArrayTable? BoolArrayData(int j) { int o = __p.__offset(50); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.BoolArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.BoolArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BoolArrayDataLength { get { int o = __p.__offset(50); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable? Int16ArrayData(int j) { int o = __p.__offset(52); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Int16ArrayDataLength { get { int o = __p.__offset(52); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable? Int32ArrayData(int j) { int o = __p.__offset(54); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Int32ArrayDataLength { get { int o = __p.__offset(54); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable? Int64ArrayData(int j) { int o = __p.__offset(56); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Int64ArrayDataLength { get { int o = __p.__offset(56); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable? EnumArrayData(int j) { int o = __p.__offset(58); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EnumArrayDataLength { get { int o = __p.__offset(58); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable? Uint16ArrayData(int j) { int o = __p.__offset(60); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Uint16ArrayDataLength { get { int o = __p.__offset(60); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable? Uint32ArrayData(int j) { int o = __p.__offset(62); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Uint32ArrayDataLength { get { int o = __p.__offset(62); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable? Uint64ArrayData(int j) { int o = __p.__offset(64); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Uint64ArrayDataLength { get { int o = __p.__offset(64); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.FloatArrayTable? FloatArrayData(int j) { int o = __p.__offset(66); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.FloatArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.FloatArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FloatArrayDataLength { get { int o = __p.__offset(66); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable? DoubleArrayData(int j) { int o = __p.__offset(68); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DoubleArrayDataLength { get { int o = __p.__offset(68); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.BaseType.StringArrayTable? StringArrayData(int j) { int o = __p.__offset(70); return o != 0 ? (ReblackVfx.FlatBuffer.BaseType.StringArrayTable?)(new ReblackVfx.FlatBuffer.BaseType.StringArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int StringArrayDataLength { get { int o = __p.__offset(70); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector2ArrayTable? Vector2ArrayData(int j) { int o = __p.__offset(72); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector2ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Vector2ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Vector2ArrayDataLength { get { int o = __p.__offset(72); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector3ArrayTable? Vector3ArrayData(int j) { int o = __p.__offset(74); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector3ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Vector3ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Vector3ArrayDataLength { get { int o = __p.__offset(74); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Vector4ArrayTable? Vector4ArrayData(int j) { int o = __p.__offset(76); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Vector4ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Vector4ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Vector4ArrayDataLength { get { int o = __p.__offset(76); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.ColorArrayTable? ColorArrayData(int j) { int o = __p.__offset(78); return o != 0 ? (ReblackVfx.FlatBuffer.Math.ColorArrayTable?)(new ReblackVfx.FlatBuffer.Math.ColorArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ColorArrayDataLength { get { int o = __p.__offset(78); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable? Matrix33ArrayData(int j) { int o = __p.__offset(80); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Matrix33ArrayDataLength { get { int o = __p.__offset(80); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable? Matrix34ArrayData(int j) { int o = __p.__offset(82); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Matrix34ArrayDataLength { get { int o = __p.__offset(82); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable? Matrix44ArrayData(int j) { int o = __p.__offset(84); return o != 0 ? (ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable?)(new ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Matrix44ArrayDataLength { get { int o = __p.__offset(84); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.QuaternionArrayTable? QuaternionArrayData(int j) { int o = __p.__offset(86); return o != 0 ? (ReblackVfx.FlatBuffer.Math.QuaternionArrayTable?)(new ReblackVfx.FlatBuffer.Math.QuaternionArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int QuaternionArrayDataLength { get { int o = __p.__offset(86); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ReblackVfx.FlatBuffer.Math.EulerArrayTable? EulerArrayData(int j) { int o = __p.__offset(88); return o != 0 ? (ReblackVfx.FlatBuffer.Math.EulerArrayTable?)(new ReblackVfx.FlatBuffer.Math.EulerArrayTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EulerArrayDataLength { get { int o = __p.__offset(88); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData> CreateGraphBaseTypeData(FlatBufferBuilder builder,
      VectorOffset byte_dataOffset = default(VectorOffset),
      VectorOffset bool_dataOffset = default(VectorOffset),
      VectorOffset int16_dataOffset = default(VectorOffset),
      VectorOffset int32_dataOffset = default(VectorOffset),
      VectorOffset int64_dataOffset = default(VectorOffset),
      VectorOffset ubyte_dataOffset = default(VectorOffset),
      VectorOffset uint16_dataOffset = default(VectorOffset),
      VectorOffset uint32_dataOffset = default(VectorOffset),
      VectorOffset uint64_dataOffset = default(VectorOffset),
      VectorOffset float_dataOffset = default(VectorOffset),
      VectorOffset double_dataOffset = default(VectorOffset),
      VectorOffset string_dataOffset = default(VectorOffset),
      VectorOffset enum_dataOffset = default(VectorOffset),
      VectorOffset vector2_dataOffset = default(VectorOffset),
      VectorOffset vector3_dataOffset = default(VectorOffset),
      VectorOffset vector4_dataOffset = default(VectorOffset),
      VectorOffset color_dataOffset = default(VectorOffset),
      VectorOffset matrix33_dataOffset = default(VectorOffset),
      VectorOffset matrix34_dataOffset = default(VectorOffset),
      VectorOffset matrix44_dataOffset = default(VectorOffset),
      VectorOffset quaternion_dataOffset = default(VectorOffset),
      VectorOffset euler_dataOffset = default(VectorOffset),
      VectorOffset byte_array_dataOffset = default(VectorOffset),
      VectorOffset bool_array_dataOffset = default(VectorOffset),
      VectorOffset int16_array_dataOffset = default(VectorOffset),
      VectorOffset int32_array_dataOffset = default(VectorOffset),
      VectorOffset int64_array_dataOffset = default(VectorOffset),
      VectorOffset enum_array_dataOffset = default(VectorOffset),
      VectorOffset uint16_array_dataOffset = default(VectorOffset),
      VectorOffset uint32_array_dataOffset = default(VectorOffset),
      VectorOffset uint64_array_dataOffset = default(VectorOffset),
      VectorOffset float_array_dataOffset = default(VectorOffset),
      VectorOffset double_array_dataOffset = default(VectorOffset),
      VectorOffset string_array_dataOffset = default(VectorOffset),
      VectorOffset vector2_array_dataOffset = default(VectorOffset),
      VectorOffset vector3_array_dataOffset = default(VectorOffset),
      VectorOffset vector4_array_dataOffset = default(VectorOffset),
      VectorOffset color_array_dataOffset = default(VectorOffset),
      VectorOffset matrix33_array_dataOffset = default(VectorOffset),
      VectorOffset matrix34_array_dataOffset = default(VectorOffset),
      VectorOffset matrix44_array_dataOffset = default(VectorOffset),
      VectorOffset quaternion_array_dataOffset = default(VectorOffset),
      VectorOffset euler_array_dataOffset = default(VectorOffset)) {
    builder.StartTable(43);
    GraphBaseTypeData.AddEulerArrayData(builder, euler_array_dataOffset);
    GraphBaseTypeData.AddQuaternionArrayData(builder, quaternion_array_dataOffset);
    GraphBaseTypeData.AddMatrix44ArrayData(builder, matrix44_array_dataOffset);
    GraphBaseTypeData.AddMatrix34ArrayData(builder, matrix34_array_dataOffset);
    GraphBaseTypeData.AddMatrix33ArrayData(builder, matrix33_array_dataOffset);
    GraphBaseTypeData.AddColorArrayData(builder, color_array_dataOffset);
    GraphBaseTypeData.AddVector4ArrayData(builder, vector4_array_dataOffset);
    GraphBaseTypeData.AddVector3ArrayData(builder, vector3_array_dataOffset);
    GraphBaseTypeData.AddVector2ArrayData(builder, vector2_array_dataOffset);
    GraphBaseTypeData.AddStringArrayData(builder, string_array_dataOffset);
    GraphBaseTypeData.AddDoubleArrayData(builder, double_array_dataOffset);
    GraphBaseTypeData.AddFloatArrayData(builder, float_array_dataOffset);
    GraphBaseTypeData.AddUint64ArrayData(builder, uint64_array_dataOffset);
    GraphBaseTypeData.AddUint32ArrayData(builder, uint32_array_dataOffset);
    GraphBaseTypeData.AddUint16ArrayData(builder, uint16_array_dataOffset);
    GraphBaseTypeData.AddEnumArrayData(builder, enum_array_dataOffset);
    GraphBaseTypeData.AddInt64ArrayData(builder, int64_array_dataOffset);
    GraphBaseTypeData.AddInt32ArrayData(builder, int32_array_dataOffset);
    GraphBaseTypeData.AddInt16ArrayData(builder, int16_array_dataOffset);
    GraphBaseTypeData.AddBoolArrayData(builder, bool_array_dataOffset);
    GraphBaseTypeData.AddByteArrayData(builder, byte_array_dataOffset);
    GraphBaseTypeData.AddEulerData(builder, euler_dataOffset);
    GraphBaseTypeData.AddQuaternionData(builder, quaternion_dataOffset);
    GraphBaseTypeData.AddMatrix44Data(builder, matrix44_dataOffset);
    GraphBaseTypeData.AddMatrix34Data(builder, matrix34_dataOffset);
    GraphBaseTypeData.AddMatrix33Data(builder, matrix33_dataOffset);
    GraphBaseTypeData.AddColorData(builder, color_dataOffset);
    GraphBaseTypeData.AddVector4Data(builder, vector4_dataOffset);
    GraphBaseTypeData.AddVector3Data(builder, vector3_dataOffset);
    GraphBaseTypeData.AddVector2Data(builder, vector2_dataOffset);
    GraphBaseTypeData.AddEnumData(builder, enum_dataOffset);
    GraphBaseTypeData.AddStringData(builder, string_dataOffset);
    GraphBaseTypeData.AddDoubleData(builder, double_dataOffset);
    GraphBaseTypeData.AddFloatData(builder, float_dataOffset);
    GraphBaseTypeData.AddUint64Data(builder, uint64_dataOffset);
    GraphBaseTypeData.AddUint32Data(builder, uint32_dataOffset);
    GraphBaseTypeData.AddUint16Data(builder, uint16_dataOffset);
    GraphBaseTypeData.AddUbyteData(builder, ubyte_dataOffset);
    GraphBaseTypeData.AddInt64Data(builder, int64_dataOffset);
    GraphBaseTypeData.AddInt32Data(builder, int32_dataOffset);
    GraphBaseTypeData.AddInt16Data(builder, int16_dataOffset);
    GraphBaseTypeData.AddBoolData(builder, bool_dataOffset);
    GraphBaseTypeData.AddByteData(builder, byte_dataOffset);
    return GraphBaseTypeData.EndGraphBaseTypeData(builder);
  }

  public static void StartGraphBaseTypeData(FlatBufferBuilder builder) { builder.StartTable(43); }
  public static void AddByteData(FlatBufferBuilder builder, VectorOffset byteDataOffset) { builder.AddOffset(0, byteDataOffset.Value, 0); }
  public static VectorOffset CreateByteDataVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateByteDataVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateByteDataVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateByteDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartByteDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddBoolData(FlatBufferBuilder builder, VectorOffset boolDataOffset) { builder.AddOffset(1, boolDataOffset.Value, 0); }
  public static VectorOffset CreateBoolDataVector(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddBool(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateBoolDataVectorBlock(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoolDataVectorBlock(FlatBufferBuilder builder, ArraySegment<bool> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoolDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<bool>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBoolDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddInt16Data(FlatBufferBuilder builder, VectorOffset int16DataOffset) { builder.AddOffset(2, int16DataOffset.Value, 0); }
  public static VectorOffset CreateInt16DataVector(FlatBufferBuilder builder, short[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddShort(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInt16DataVectorBlock(FlatBufferBuilder builder, short[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt16DataVectorBlock(FlatBufferBuilder builder, ArraySegment<short> data) { builder.StartVector(2, data.Count, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt16DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<short>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt16DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
  public static void AddInt32Data(FlatBufferBuilder builder, VectorOffset int32DataOffset) { builder.AddOffset(3, int32DataOffset.Value, 0); }
  public static VectorOffset CreateInt32DataVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInt32DataVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt32DataVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt32DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt32DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInt64Data(FlatBufferBuilder builder, VectorOffset int64DataOffset) { builder.AddOffset(4, int64DataOffset.Value, 0); }
  public static VectorOffset CreateInt64DataVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInt64DataVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt64DataVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt64DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt64DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddUbyteData(FlatBufferBuilder builder, VectorOffset ubyteDataOffset) { builder.AddOffset(5, ubyteDataOffset.Value, 0); }
  public static VectorOffset CreateUbyteDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUbyteDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUbyteDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUbyteDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUbyteDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddUint16Data(FlatBufferBuilder builder, VectorOffset uint16DataOffset) { builder.AddOffset(6, uint16DataOffset.Value, 0); }
  public static VectorOffset CreateUint16DataVector(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddUshort(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUint16DataVectorBlock(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint16DataVectorBlock(FlatBufferBuilder builder, ArraySegment<ushort> data) { builder.StartVector(2, data.Count, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint16DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<ushort>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint16DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
  public static void AddUint32Data(FlatBufferBuilder builder, VectorOffset uint32DataOffset) { builder.AddOffset(7, uint32DataOffset.Value, 0); }
  public static VectorOffset CreateUint32DataVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUint32DataVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint32DataVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint32DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint32DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUint64Data(FlatBufferBuilder builder, VectorOffset uint64DataOffset) { builder.AddOffset(8, uint64DataOffset.Value, 0); }
  public static VectorOffset CreateUint64DataVector(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddUlong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUint64DataVectorBlock(FlatBufferBuilder builder, ulong[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint64DataVectorBlock(FlatBufferBuilder builder, ArraySegment<ulong> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint64DataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<ulong>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint64DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddFloatData(FlatBufferBuilder builder, VectorOffset floatDataOffset) { builder.AddOffset(9, floatDataOffset.Value, 0); }
  public static VectorOffset CreateFloatDataVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateFloatDataVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFloatDataVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFloatDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFloatDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDoubleData(FlatBufferBuilder builder, VectorOffset doubleDataOffset) { builder.AddOffset(10, doubleDataOffset.Value, 0); }
  public static VectorOffset CreateDoubleDataVector(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddDouble(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDoubleDataVectorBlock(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDoubleDataVectorBlock(FlatBufferBuilder builder, ArraySegment<double> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDoubleDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<double>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDoubleDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddStringData(FlatBufferBuilder builder, VectorOffset stringDataOffset) { builder.AddOffset(11, stringDataOffset.Value, 0); }
  public static VectorOffset CreateStringDataVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStringDataVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStringDataVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStringDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStringDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEnumData(FlatBufferBuilder builder, VectorOffset enumDataOffset) { builder.AddOffset(12, enumDataOffset.Value, 0); }
  public static VectorOffset CreateEnumDataVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEnumDataVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnumDataVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnumDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEnumDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVector2Data(FlatBufferBuilder builder, VectorOffset vector2DataOffset) { builder.AddOffset(13, vector2DataOffset.Value, 0); }
  public static void StartVector2DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddVector3Data(FlatBufferBuilder builder, VectorOffset vector3DataOffset) { builder.AddOffset(14, vector3DataOffset.Value, 0); }
  public static void StartVector3DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddVector4Data(FlatBufferBuilder builder, VectorOffset vector4DataOffset) { builder.AddOffset(15, vector4DataOffset.Value, 0); }
  public static void StartVector4DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddColorData(FlatBufferBuilder builder, VectorOffset colorDataOffset) { builder.AddOffset(16, colorDataOffset.Value, 0); }
  public static void StartColorDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddMatrix33Data(FlatBufferBuilder builder, VectorOffset matrix33DataOffset) { builder.AddOffset(17, matrix33DataOffset.Value, 0); }
  public static void StartMatrix33DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(48, numElems, 4); }
  public static void AddMatrix34Data(FlatBufferBuilder builder, VectorOffset matrix34DataOffset) { builder.AddOffset(18, matrix34DataOffset.Value, 0); }
  public static void StartMatrix34DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(48, numElems, 4); }
  public static void AddMatrix44Data(FlatBufferBuilder builder, VectorOffset matrix44DataOffset) { builder.AddOffset(19, matrix44DataOffset.Value, 0); }
  public static void StartMatrix44DataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(64, numElems, 4); }
  public static void AddQuaternionData(FlatBufferBuilder builder, VectorOffset quaternionDataOffset) { builder.AddOffset(20, quaternionDataOffset.Value, 0); }
  public static void StartQuaternionDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddEulerData(FlatBufferBuilder builder, VectorOffset eulerDataOffset) { builder.AddOffset(21, eulerDataOffset.Value, 0); }
  public static void StartEulerDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddByteArrayData(FlatBufferBuilder builder, VectorOffset byteArrayDataOffset) { builder.AddOffset(22, byteArrayDataOffset.Value, 0); }
  public static VectorOffset CreateByteArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.ByteArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateByteArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.ByteArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateByteArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.ByteArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateByteArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.ByteArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartByteArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBoolArrayData(FlatBufferBuilder builder, VectorOffset boolArrayDataOffset) { builder.AddOffset(23, boolArrayDataOffset.Value, 0); }
  public static VectorOffset CreateBoolArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.BoolArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBoolArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.BoolArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoolArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.BoolArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBoolArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.BoolArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBoolArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInt16ArrayData(FlatBufferBuilder builder, VectorOffset int16ArrayDataOffset) { builder.AddOffset(24, int16ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateInt16ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInt16ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt16ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt16ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Int16ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt16ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInt32ArrayData(FlatBufferBuilder builder, VectorOffset int32ArrayDataOffset) { builder.AddOffset(25, int32ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateInt32ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInt32ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt32ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt32ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt32ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInt64ArrayData(FlatBufferBuilder builder, VectorOffset int64ArrayDataOffset) { builder.AddOffset(26, int64ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateInt64ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInt64ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt64ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInt64ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Int64ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInt64ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEnumArrayData(FlatBufferBuilder builder, VectorOffset enumArrayDataOffset) { builder.AddOffset(27, enumArrayDataOffset.Value, 0); }
  public static VectorOffset CreateEnumArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEnumArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnumArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnumArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Int32ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEnumArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUint16ArrayData(FlatBufferBuilder builder, VectorOffset uint16ArrayDataOffset) { builder.AddOffset(28, uint16ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateUint16ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUint16ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint16ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint16ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint16ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUint32ArrayData(FlatBufferBuilder builder, VectorOffset uint32ArrayDataOffset) { builder.AddOffset(29, uint32ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateUint32ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUint32ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint32ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint32ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint32ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUint64ArrayData(FlatBufferBuilder builder, VectorOffset uint64ArrayDataOffset) { builder.AddOffset(30, uint64ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateUint64ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUint64ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint64ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUint64ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUint64ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFloatArrayData(FlatBufferBuilder builder, VectorOffset floatArrayDataOffset) { builder.AddOffset(31, floatArrayDataOffset.Value, 0); }
  public static VectorOffset CreateFloatArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.FloatArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFloatArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.FloatArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFloatArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.FloatArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFloatArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.FloatArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFloatArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDoubleArrayData(FlatBufferBuilder builder, VectorOffset doubleArrayDataOffset) { builder.AddOffset(32, doubleArrayDataOffset.Value, 0); }
  public static VectorOffset CreateDoubleArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDoubleArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDoubleArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDoubleArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.DoubleArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDoubleArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStringArrayData(FlatBufferBuilder builder, VectorOffset stringArrayDataOffset) { builder.AddOffset(33, stringArrayDataOffset.Value, 0); }
  public static VectorOffset CreateStringArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.StringArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateStringArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.BaseType.StringArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStringArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.BaseType.StringArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStringArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.BaseType.StringArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStringArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVector2ArrayData(FlatBufferBuilder builder, VectorOffset vector2ArrayDataOffset) { builder.AddOffset(34, vector2ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateVector2ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector2ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateVector2ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector2ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector2ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Vector2ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector2ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Vector2ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVector2ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVector3ArrayData(FlatBufferBuilder builder, VectorOffset vector3ArrayDataOffset) { builder.AddOffset(35, vector3ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateVector3ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector3ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateVector3ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector3ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector3ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Vector3ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector3ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Vector3ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVector3ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVector4ArrayData(FlatBufferBuilder builder, VectorOffset vector4ArrayDataOffset) { builder.AddOffset(36, vector4ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateVector4ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateVector4ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector4ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateVector4ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Vector4ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartVector4ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddColorArrayData(FlatBufferBuilder builder, VectorOffset colorArrayDataOffset) { builder.AddOffset(37, colorArrayDataOffset.Value, 0); }
  public static VectorOffset CreateColorArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.ColorArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateColorArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.ColorArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateColorArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.ColorArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateColorArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.ColorArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartColorArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMatrix33ArrayData(FlatBufferBuilder builder, VectorOffset matrix33ArrayDataOffset) { builder.AddOffset(38, matrix33ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateMatrix33ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMatrix33ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix33ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix33ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Matrix33ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMatrix33ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMatrix34ArrayData(FlatBufferBuilder builder, VectorOffset matrix34ArrayDataOffset) { builder.AddOffset(39, matrix34ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateMatrix34ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMatrix34ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix34ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix34ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Matrix34ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMatrix34ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMatrix44ArrayData(FlatBufferBuilder builder, VectorOffset matrix44ArrayDataOffset) { builder.AddOffset(40, matrix44ArrayDataOffset.Value, 0); }
  public static VectorOffset CreateMatrix44ArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMatrix44ArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix44ArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMatrix44ArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.Matrix44ArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMatrix44ArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddQuaternionArrayData(FlatBufferBuilder builder, VectorOffset quaternionArrayDataOffset) { builder.AddOffset(41, quaternionArrayDataOffset.Value, 0); }
  public static VectorOffset CreateQuaternionArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateQuaternionArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateQuaternionArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateQuaternionArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.QuaternionArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartQuaternionArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEulerArrayData(FlatBufferBuilder builder, VectorOffset eulerArrayDataOffset) { builder.AddOffset(42, eulerArrayDataOffset.Value, 0); }
  public static VectorOffset CreateEulerArrayDataVector(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.EulerArrayTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEulerArrayDataVectorBlock(FlatBufferBuilder builder, Offset<ReblackVfx.FlatBuffer.Math.EulerArrayTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEulerArrayDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<ReblackVfx.FlatBuffer.Math.EulerArrayTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEulerArrayDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<ReblackVfx.FlatBuffer.Math.EulerArrayTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEulerArrayDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData> EndGraphBaseTypeData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ReblackVfx.FlatBuffer.BaseType.GraphBaseTypeData>(o);
  }
}


static public class GraphBaseTypeDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*ByteData*/, 1 /*sbyte*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*BoolData*/, 1 /*bool*/, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Int16Data*/, 2 /*short*/, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Int32Data*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*Int64Data*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*UbyteData*/, 1 /*byte*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*Uint16Data*/, 2 /*ushort*/, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*Uint32Data*/, 4 /*uint*/, false)
      && verifier.VerifyVectorOfData(tablePos, 20 /*Uint64Data*/, 8 /*ulong*/, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*FloatData*/, 4 /*float*/, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*DoubleData*/, 8 /*double*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 26 /*StringData*/, false)
      && verifier.VerifyVectorOfData(tablePos, 28 /*EnumData*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 30 /*Vector2Data*/, 16 /*ReblackVfx.FlatBuffer.Math.Vector4*/, false)
      && verifier.VerifyVectorOfData(tablePos, 32 /*Vector3Data*/, 16 /*ReblackVfx.FlatBuffer.Math.Vector4*/, false)
      && verifier.VerifyVectorOfData(tablePos, 34 /*Vector4Data*/, 16 /*ReblackVfx.FlatBuffer.Math.Vector4*/, false)
      && verifier.VerifyVectorOfData(tablePos, 36 /*ColorData*/, 16 /*ReblackVfx.FlatBuffer.Math.Vector4*/, false)
      && verifier.VerifyVectorOfData(tablePos, 38 /*Matrix33Data*/, 48 /*ReblackVfx.FlatBuffer.Math.Matrix33*/, false)
      && verifier.VerifyVectorOfData(tablePos, 40 /*Matrix34Data*/, 48 /*ReblackVfx.FlatBuffer.Math.Matrix34*/, false)
      && verifier.VerifyVectorOfData(tablePos, 42 /*Matrix44Data*/, 64 /*ReblackVfx.FlatBuffer.Math.Matrix44*/, false)
      && verifier.VerifyVectorOfData(tablePos, 44 /*QuaternionData*/, 16 /*ReblackVfx.FlatBuffer.Math.Quaternion*/, false)
      && verifier.VerifyVectorOfData(tablePos, 46 /*EulerData*/, 16 /*ReblackVfx.FlatBuffer.Math.Euler*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 48 /*ByteArrayData*/, ReblackVfx.FlatBuffer.BaseType.ByteArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 50 /*BoolArrayData*/, ReblackVfx.FlatBuffer.BaseType.BoolArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 52 /*Int16ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Int16ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 54 /*Int32ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Int32ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 56 /*Int64ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Int64ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 58 /*EnumArrayData*/, ReblackVfx.FlatBuffer.BaseType.Int32ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 60 /*Uint16ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Uint16ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 62 /*Uint32ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Uint32ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 64 /*Uint64ArrayData*/, ReblackVfx.FlatBuffer.BaseType.Uint64ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 66 /*FloatArrayData*/, ReblackVfx.FlatBuffer.BaseType.FloatArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 68 /*DoubleArrayData*/, ReblackVfx.FlatBuffer.BaseType.DoubleArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 70 /*StringArrayData*/, ReblackVfx.FlatBuffer.BaseType.StringArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 72 /*Vector2ArrayData*/, ReblackVfx.FlatBuffer.Math.Vector2ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 74 /*Vector3ArrayData*/, ReblackVfx.FlatBuffer.Math.Vector3ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 76 /*Vector4ArrayData*/, ReblackVfx.FlatBuffer.Math.Vector4ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 78 /*ColorArrayData*/, ReblackVfx.FlatBuffer.Math.ColorArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 80 /*Matrix33ArrayData*/, ReblackVfx.FlatBuffer.Math.Matrix33ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 82 /*Matrix34ArrayData*/, ReblackVfx.FlatBuffer.Math.Matrix34ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 84 /*Matrix44ArrayData*/, ReblackVfx.FlatBuffer.Math.Matrix44ArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 86 /*QuaternionArrayData*/, ReblackVfx.FlatBuffer.Math.QuaternionArrayTableVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 88 /*EulerArrayData*/, ReblackVfx.FlatBuffer.Math.EulerArrayTableVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
