// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ReblackVfx.FlatBuffer.BaseType
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Value : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Value __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ValueType { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int ValueIndex { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<ReblackVfx.FlatBuffer.BaseType.Value> CreateValue(FlatBufferBuilder builder, int ValueType, int ValueIndex) {
    builder.Prep(4, 8);
    builder.PutInt(ValueIndex);
    builder.PutInt(ValueType);
    return new Offset<ReblackVfx.FlatBuffer.BaseType.Value>(builder.Offset);
  }
}


}
